# Generated by Django 5.2.1 on 2025-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('full', 'Full Payment'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly (Every 3 Months)')], default='full', max_length=20),
        ),
    ]
