# Generated by Django 5.2.1 on 2025-05-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
