# Generated by Django 5.2.1 on 2025-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
